Adding and updating windows script
mcode/cql-testing-harness pull request #2
Opened 2021-04-15 17:43 UTC by dmendelowitz

Adding the windows script to the now separated testing harness. This is very similar to the windows script on the mcode-cql repo, but now it takes the command line argument "-t" to specify the test folder and calls buildElm.js and jest directly instead of using the yarn scripts. You should be able to test this by changing the dependency in the mcode-cql repo (after the refactor is merged there) to point to a local file of this branch.

2021-04-15 18:10 UTC, mgramigna requested changes

2021-04-15 18:10 UTC, mgramigna commented on src/scripts/run_tests.bat
> +call jest --testPathPattern=%TEST_DIR%
I was testing this on the VM, and looks like it gets mad if jest isn't in the user's path. I imagine this will happen in the shell script too. here is a workaround that I think we should include in both this file and `run_tests.sh` if you don't mind updating it there as well

```suggestion
call npx jest --testPathPattern=%TEST_DIR%
```

`npx` will run the jest command through npm directly and will not require anything to be in the path or installed globally.

2021-04-15 18:12 UTC, Dtphelan1 commented on src/scripts/run_tests.bat
> +call jest --testPathPattern=%TEST_DIR%
😮

2021-04-15 18:17 UTC, dmendelowitz commented on src/scripts/run_tests.bat
> +call jest --testPathPattern=%TEST_DIR%
Makes sense, I was having some weirdness with jest too, but it somehow ended up working, but I'm glad I know the reason now

2021-04-15 19:29 UTC, mgramigna commented
Would you mind making the same `npx` change to the `sh` script just to be consistent?

2021-04-15 19:49 UTC, mgramigna approved these changes
Looks good. Great work

2021-04-16 15:46 UTC, jafeltra approved these changes
This looks good! I had tested with Matt on the VM and I ran the `.sh` script locally and it all works as expected.

2021-04-16 15:51 UTC, merged